name: release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    environment: automated-release
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Use Node.js 20
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Move release to draft
      run: gh release edit "$TAG_NAME" --draft=true
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Install Playwright browser
      run: npx playwright install --with-deps chromium

    - name: Test
      run: npm test

    - name: Create release archive
      run: |
        zip -r lib.zip lib *.md LICENSE package.json package-lock.json

    - name: Upload production artifacts
      run: |
        gh release upload "$TAG_NAME" "lib.zip"
        gh release edit "$TAG_NAME" --draft=false
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
